# Site settings
title: sun raise here
email: spatriotc@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: ee/cs rookie

# Social icons
facebook: username
linkedin: username
github: username
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
